### ISSUE TITLE
Help with running the examples?

### ISSUE THREAD

**Issue by timothy-barry** [pinellolab/crispr-bean#33]
Hi,

Congrats on the release of this package. It seems that this tool will be quite useful for the CRISPR community. I especially like the functionality for accounting for heterogeneity in editing efficiency across gRNAs.

I am trying to work through the tutorials but am having a bit of difficulty. In particular, the [variant sorting screen tutorial](https://pinellolab.github.io/crispr-bean/tutorial_gwas.html) uses an example "test file", but I am unable to locate this test file. Is the idea that I should download the `test` directory from [here](https://github.com/pinellolab/crispr-bean/tree/main/tests/data) and then update the file paths on my machine?

Thanks,
Tim

**Comment by jykr** [comment]
Hi Tim,

Thanks for your kind words and trying BEAN out! 

Tutorials are illustrative and doesn't exactly match with the test files as it's quite tricky to include all input files for the entire workflow (namely .fq files will be too large to include as test files). The comprehensive usage example with example files can be seen in [`tests` folder](https://github.com/pinellolab/crispr-bean/tree/main/tests). I can see this is confusing and will work on matching those scripts with files included in the repo!

That being said, if you're interested in trying out later steps than `bean count-samples`, you can run the workflow by using the following: 
```
screen_id=var_mini_screen
working_dir=tests/data/

# profile
bean profile tests/data/var_mini_screen.h5ad --pam-col '5-nt PAM'

# 2. QC samples & guides
bean qc \
  ${working_dir}/var_mini_screen.h5ad             `# Input ReporterScreen .h5ad file path` \
  -o ${working_dir}/var_mini_screen_masked.h5ad   `# Output ReporterScreen .h5ad file path` \
  -r ${working_dir}/qc_report_${screen_id}                `# Prefix for QC report` \
  -b                                       ` # Remove replicates with no good samples.

# 3. Quantify variant effect
bean run sorting variant \
    ${working_dir}/var_mini_screen_masked.h5ad \
    -o ${working_dir}/ \
    --fit-negctrl \
    --scale-by-acc \
    --acc-bw-path tests/data/accessibility_signal_chr6.bw
```

Jayoung

**Comment by jykr** [comment]
Updated the tutorial pages too!

**Comment by timothy-barry** [comment]
Hi Jayoung,

Thanks for making this update. I tried running the above script, and I get the error "Unable to open file var_mini_screen_masked.h5ad." It looks like this file might not be in the `tests/data` directory?

**Comment by jykr** [comment]
That is intermediate file generated by running `bean qc`. Following the tutorial or running `pytest --sparse-ordering` will generate all intermediate files & sample results.

**Comment by timothy-barry** [comment]
Ah, got it. I think I installed the software incorrectly. I will try to download again and then get back to you. Thanks!
